[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "climate_lib"
#version = "0.1.0"
dynamic = ["version"]
dependencies = ["numpy",
    "pandas",
    "xarray",
    "scipy",
    "dask",
    "metpy",
    "matplotlib",
    "cartopy",
    "scikit-learn",
    "geocat.comp",
    "scipy",
    "netCDF4",
    "cftime",
    ]
authors = [{name = "Dhairya Chopra", email = "dhairyachopra2005@gmail.com"}]
description = "Climate Functions for the M. Lague Lab"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]

[tool.hatch.version]
source = "vcs"  # Tells Hatchling to look at Git Tags for the version number

[tool.hatch.version.raw-options]
# This creates a file at build-time so Python can read the version at runtime
write_to = "src/climate_lib/_version.py" 

[tool.semantic_release]
branches.main = { match = "main" }
version_source = "tag"
build_command = ""

[project.urls]
Homepage = "https://github.com/GGBoss101/climate_lib"
Issues = "https://github.com/GGBoss101/climate_lib/issues"